"""
Prompts Package.

Centralized location for reusable prompt components and instructions.
"""
from .common import (
    JSON_OUTPUT_STRICT,
    JSON_OUTPUT_RELAXED,
    OBJECTIVITY_INSTRUCTION,
    COMPREHENSIVENESS_INSTRUCTION,
    CITATION_INSTRUCTION,
    SOURCE_QUALITY_INSTRUCTION,
    EXCLUSION_CRITERIA_ARGUMENTS,
    STANCE_DEFINITIONS,
    SCHEMA_ARGUMENT,
    SCHEMA_SOURCE_REFERENCE,
    SCHEMA_PROS_CONS,
)

__all__ = [
    "JSON_OUTPUT_STRICT",
    "JSON_OUTPUT_RELAXED",
    "OBJECTIVITY_INSTRUCTION",
    "COMPREHENSIVENESS_INSTRUCTION",
    "CITATION_INSTRUCTION",
    "SOURCE_QUALITY_INSTRUCTION",
    "EXCLUSION_CRITERIA_ARGUMENTS",
    "STANCE_DEFINITIONS",
    "SCHEMA_ARGUMENT",
    "SCHEMA_SOURCE_REFERENCE",
    "SCHEMA_PROS_CONS",
]
