"""
Constants Package.

All constants organized by domain. Import from here for convenience:

    from app.constants import LLM_TEMP_PROS_CONS_ANALYSIS
    from app.constants.security import RATE_LIMIT_PER_IP_PER_MINUTE
"""

from .security import (
    RATE_LIMIT_PER_IP_PER_MINUTE,
    RATE_LIMIT_PER_KEY_PER_HOUR,
    MAX_AUTH_FAILURES_BEFORE_BLOCK,
    AUTH_FAILURE_WINDOW_SECONDS,
    IP_BLOCK_DURATION_SECONDS,
    MAX_REQUEST_BODY_BYTES,
    PROMPT_INJECTION_PATTERNS,
    SECURITY_HEADERS,
)

from .analysis import (
    MODE_CONFIG,
    CONSENSUS_STRONG_THRESHOLD,
    CONSENSUS_MODERATE_THRESHOLD,
    CONSENSUS_CONTESTED_THRESHOLD,
)

from .llm import (
    OPENAI_MODEL_FAST,
    OPENAI_MODEL_SMART,
    LLM_TEMP_PROS_CONS_ANALYSIS,
    LLM_TEMP_RELIABILITY_AGGREGATION,
    LLM_TEMP_TOPIC_CLASSIFICATION,
    LLM_TEMP_QUERY_GENERATION,
    LLM_TEMP_RELEVANCE_SCREENING,
)

from .content_limits import (
    PROS_CONS_MAX_CONTENT_LENGTH,
    PROS_CONS_MIN_PARTIAL_CONTENT,
    AGGREGATE_MAX_PROS_PER_ARG,
    AGGREGATE_MAX_CONS_PER_ARG,
    AGGREGATE_MAX_CLAIM_LENGTH,
    AGGREGATE_MAX_ARGUMENT_LENGTH,
    AGGREGATE_MAX_ITEMS_TEXT_LENGTH,
    PUBMED_SNIPPET_MAX_LENGTH,
    PUBMED_MAX_AUTHORS_DISPLAYED,
    FULLTEXT_MAX_CONTENT_LENGTH,
    SCREENING_TITLE_MAX_LENGTH,
    SCREENING_SNIPPET_MAX_LENGTH,
    SCREENING_MAX_TOKENS,
)

from .scoring import (
    RELIABILITY_NO_SOURCES,
    RELIABILITY_MAX_FALLBACK,
    RELIABILITY_BASE_SCORE,
    RELIABILITY_PER_SOURCE_INCREMENT,
    RELEVANCE_THRESHOLD_HIGH,
    RELEVANCE_THRESHOLD_MEDIUM_MIN,
    RELEVANCE_DEFAULT_MIN_SCORE,
    RELEVANCE_DEFAULT_MAX_RESULTS,
)

from .retry import (
    DEFAULT_RETRY_MAX_ATTEMPTS,
    DEFAULT_RETRY_BASE_DELAY,
    DEFAULT_RETRY_BACKOFF_FACTOR,
    DEFAULT_RETRY_MAX_DELAY,
    QUERY_GENERATOR_MAX_RETRY_ATTEMPTS,
    QUERY_GENERATOR_BASE_DELAY,
    WORLD_BANK_MAX_RETRY_ATTEMPTS,
    WORLD_BANK_BASE_DELAY,
    WORLD_BANK_FETCH_MAX_RETRY_ATTEMPTS,
    WORLD_BANK_FETCH_BASE_DELAY,
)

from .text_processing import (
    KEYWORD_MIN_LENGTH,
    QUERY_GEN_MIN_WORD_LENGTH,
    QUERY_GEN_MAX_KEYWORDS,
    ARXIV_MIN_WORD_LENGTH_FALLBACK,
    ARXIV_MAX_KEYWORDS_FALLBACK,
    FRENCH_STOP_WORDS,
    ENGLISH_STOP_WORDS,
    COMMON_STOP_WORDS_EN_FR,
)

from .api import (
    DEFAULT_TIMEOUT_HTTPX,
    PUBMED_REQUEST_TIMEOUT,
    PUBMED_FETCH_TIMEOUT,
    PUBMED_RATE_LIMIT_WITHOUT_KEY,
    PUBMED_RATE_LIMIT_WITH_KEY,
    RATE_LIMIT_OECD_CALLS_PER_SEC,
    RATE_LIMIT_WORLD_BANK_CALLS_PER_SEC,
    RATE_LIMIT_ARXIV_CALLS_PER_SEC,
    RATE_LIMIT_PUBMED_CALLS_PER_SEC,
    RATE_LIMIT_SEMANTIC_SCHOLAR_CALLS_PER_SEC,
    DEFAULT_CIRCUIT_BREAKER_THRESHOLD,
    CIRCUIT_BREAKER_RECOVERY_TIMEOUT_OECD,
    CIRCUIT_BREAKER_RECOVERY_TIMEOUT_ACADEMIC,
)

from .research import (
    PUBMED_DEFAULT_MAX_RESULTS,
    ARXIV_DEFAULT_MAX_RESULTS,
    OECD_DEFAULT_MAX_RESULTS,
    WORLD_BANK_DEFAULT_YEARS,
    WORLD_BANK_DEFAULT_MAX_INDICATORS,
    WORLD_BANK_MRV_YEARS,
    WORLD_BANK_MAX_KEYWORDS,
    WORLD_BANK_MAX_COUNTRIES,
    PARALLEL_RESEARCH_MAX_WORKERS,
    OECD_KEYWORD_MATCH_SCORE,
    OECD_NAME_WORD_MATCH_SCORE,
    OECD_DESC_WORD_MATCH_SCORE,
    OECD_TOP_MATCH_LIMIT,
)
