"""
Research Configuration Constants.

Default values for research sources and parallel processing.
"""

PUBMED_DEFAULT_MAX_RESULTS = 5
ARXIV_DEFAULT_MAX_RESULTS = 5
OECD_DEFAULT_MAX_RESULTS = 3
WORLD_BANK_DEFAULT_YEARS = 1
WORLD_BANK_DEFAULT_MAX_INDICATORS = 3
WORLD_BANK_MRV_YEARS = 5
WORLD_BANK_MAX_KEYWORDS = 5
WORLD_BANK_MAX_COUNTRIES = 5

PARALLEL_RESEARCH_MAX_WORKERS = 10

OECD_KEYWORD_MATCH_SCORE = 2
OECD_NAME_WORD_MATCH_SCORE = 1.5
OECD_DESC_WORD_MATCH_SCORE = 1
OECD_TOP_MATCH_LIMIT = 3
